### PR TITLE
Comment out last multiAZ flag assert

### PR DESCRIPTION
**Pull request by brucegucode**
Issue #, if available:

Description of changes:
Comment out last multiAZ flag assertion

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]

**Comment by brucegucode** [comment]
hmm, looks like it will fail when saz->maz flipped once, i will remove assert for second flip then

**Comment by brucegucode** [comment]
Ah, it's the assert tag value, should match with controller version too

**Comment by jaypipes** [comment]
@brucegucode yeah, we need to use the [`tags.assert_equal_without_ack_tags()`](https://github.com/aws-controllers-k8s/test-infra/blob/58ffb067d7c400ffbd0d470e975056efdc9e4965/src/acktest/tags.py#L119) function from the upstream test-infra package.

If not, we need to use the [`test.e2e.tags.clean`](https://github.com/aws-controllers-k8s/rds-controller/blob/f0864aecc24664b3ef8c3eed672addead0d6feaa/test/e2e/tag.py#L22) function.

**Comment by jaypipes** [comment]
@brucegucode the reason the tag update isn't working is because [`compareTags` from `templates/hooks/db_instance/delta_pre_compare.go.tpl`](https://github.com/aws-controllers-k8s/rds-controller/blob/f0864aecc24664b3ef8c3eed672addead0d6feaa/templates/hooks/db_instance/delta_pre_compare.go.tpl#L13 ) is no longer being called. This is no longer being called because instead of using the template, the `delta_pre_compare` hook was [overridden with custom code](https://github.com/aws-controllers-k8s/rds-controller/blob/f0864aecc24664b3ef8c3eed672addead0d6feaa/generator.yaml#L203) in PR #95 while I was on vacation :)

**Pull request closed without merging**
