### PR TITLE
Release artifacts for release v1.1.0

### PR DESCRIPTION
**Pull request by A-Hilaly**
Release artifacts for release v1.1.0

Signed-off-by: Amine Hilaly <hilalyamine@gmail.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jljaco** [comment]
/hold

I'd like to finish with #133 before this release

**Comment by A-Hilaly** [comment]
@jljaco this should have been shipped with #138 :) - we can make a patch or minor release for both #133 (and maybe #140)

**Review by jljaco — APPROVED** [review]
looks good to me pending all tests still passing

**Pull request merged**
