### PR TITLE
update to ACK runtime v0.19.0

### PR DESCRIPTION
**Pull request by jaypipes**
Brings in the ACK runtime v0.19.0 and ignores tags for GlobalCluster
resource (which doesn't have any tags).

Signed-off-by: Jay Pipes <jaypipes@gmail.com>

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brucegucode** [comment]
I'm seeing bunch of modifyDbInstance call.

In the runtime log, CopyTagsToSnapshot takes prettty long time to sync 
`
1.6548894881786463e+09	INFO	ackrt	desired resource state has changed	{"account": "274006911594", "role": "", "region": "us-west-2", "kind": "DBInstance", "namespace": "default", "name": "pg14-t3-micro-hgl9ui", "is_adopted": false, "generation": 814, "diff": [{"Path":{"Parts":["Spec","CopyTagsToSnapshot"]},"A":false,"B":true}]}
`

**Comment by jaypipes** [comment]
> I rechecked the api call requested from controller, looks like controller is making modify db instance call with `copyTagsToSnapshot=true` and then `copyTagsToSnapshot=false` repeatedly. wondering why controller not make consistent call (copyTagsToSnapshot=true) here ?
> 
> like Start Time2022-06-10 19:31:28 UTC "copyTagsToSnapshot": false, Start Time2022-06-10 19:31:27 UTC "copyTagsToSnapshot": true, Start Time2022-06-10 19:31:26 UTC "copyTagsToSnapshot": false, Start Time2022-06-10 19:31:26 UTC "copyTagsToSnapshot": true, Start Time2022-06-10 19:31:25 UTC "copyTagsToSnapshot": false,

And why the controller would be making a call to modify db instance every second? :(

**Comment by RedbackThomson** [comment]
@jaypipes I have moved the `tags.clean` logic into `acktest` because we'll surely need it elsewhere. Could you update your `requirements.txt` file and use the new util? Thanks https://github.com/aws-controllers-k8s/test-infra/pull/220

**Comment by vijtrip2** [comment]
closing in favor of v0.19.1 release

**Pull request closed without merging**
