### PR TITLE
Fix: unknown parameter error fix for DBClusterParameterGroup and DBPa…

### PR DESCRIPTION
**Pull request by riddhi2910**
…rameterGroup

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1847

Description of changes:

The error after removing an unknown parameter was not getting removed and the ack rds controller was not able to get out of the terminal error, making the Get( error return into the nonterminal error resolved the issue of reconciling. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by riddhi2910** [comment]
@a-hilaly

**Comment by riddhi2910** [comment]
@a-hilaly whats next?

**Comment by a-hilaly** [comment]
@riddhi2910 the `test_disable_cloudwatch_logs_exports` test is flaky. We can just rerun the tests here until we have a fix for it
/retest

**Comment by riddhi2910** [comment]
@a-hilaly closing this and will get approval from my company to do open source contribution and create a PR

**Pull request closed without merging**
