### PR TITLE
remove dev preview from olm file in preparation for GA

### PR DESCRIPTION
**Pull request by acornett21**
Issue #, if available:
NA

Description of changes:
Removing the dev preview verbiage from the OLM config file in preparation for this controller to go GA

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Signed-off-by: Adam D. Cornett <adc@redhat.com>

### CODE REVIEW

**Review by jkatz — APPROVED** [review]

**Comment by jaypipes** [comment]
/hold

Will approve this right after the AppSec signoff today.

**Pull request merged**
